# Commands to start on workspace startup
tasks:
  - name: Preparing Environment
    init: | 
      make php
      make
      go install
      echo "Try running go run main.go auth:api-token-login"
      echo "Also, you may run the following: alias platfarm=\"go run main.go\""


# Ports to expose on workspace startup
ports:
  - port: 5000
    name: Platform Login Port
    description: The port to map `platform login` to.